# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "pip"
    # Look for files in the `root` directory
    directory: "/"
    # Check the updates every day (weekdays)
    schedule:
      interval: "daily"